# Generated by moving KaomojiWindow._apply_styles out of main.py.
# Keep this function behavior-compatible with the original method.
def apply_window_styles(self):
        theme = self.config.get("theme", "light")
        if theme == "dark":
            qss = """
            #panel {
                background: transparent;
                border: none;
            }
            #titlebar {
                background: transparent;
                border: none;
            }
            #pinIcon { color: #e4e0d0; font-size: 14px; }
            * { font-family: "Microsoft YaHei UI", "Microsoft YaHei", sans-serif; }
            QLabel { color: #fff5d6; }
            QToolButton {
                background: transparent;
                color: #fff5d6;
                border: 1px solid transparent;
                border-radius: 9px;
                padding: 5px 12px;
                font-size: 13px;
                font-weight: 600;
            }
            QPushButton {
                background: transparent;
                color: #fff5d6;
                border: none;
                padding: 5px 12px;
                font-size: 13px;
                font-weight: 600;
            }
            QToolButton:hover {
                background: rgba(217, 179, 104, 0.12);
                border-color: transparent;
                color: #d9b368;
            }
            QPushButton:hover {
                background: transparent;
                border: none;
                color: #d9b368;
            }
            QToolButton:pressed {
                background: rgba(217, 179, 104, 0.25);
            }
            QPushButton:pressed {
                background: transparent;
                border: none;
            }
            #titlebar QToolButton {
                padding: 0px;
                font-family: "Segoe UI Symbol", "Microsoft YaHei UI", sans-serif;
                font-size: 15px;
            }
            QToolButton#titleIconButton {
                font-size: 16px;
            }
            QToolButton#closeButton {
                padding: 0px;
                font-size: 18px;
            }
            QToolButton#closeButton:hover { background: #f04848; color: white; border-color: transparent; }
            QTabBar::tab {
                color: #a6adc8;
                background: transparent;
                padding: 8px 16px 12px 16px;
                border-radius: 9px;
                margin-right: 4px;
                border: 1px solid transparent;
                font-size: 14px;
                font-weight: 600;
            }
            QTabBar::tab:hover {
                color: #ffdda1;
                background: rgba(217, 179, 104, 0.08);
            }
            QTabBar::tab:selected {
                color: #d9b368;
                background: transparent;
            }
            QScrollArea, QWidget { background: transparent; }
            QScrollBar:vertical {
                background: transparent;
                width: 8px;
                margin: 4px 1px 4px 1px;
            }
            QScrollBar::handle:vertical {
                background: rgba(217, 179, 104, 0.22);
                border-radius: 4px;
                min-height: 24px;
            }
            QScrollBar::handle:vertical:hover {
                background: rgba(217, 179, 104, 0.45);
            }
            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,
            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {
                height: 0px;
                background: transparent;
            }
            QScrollBar:horizontal {
                height: 0px;
                background: transparent;
            }
            QScrollBar::handle:horizontal,
            QScrollBar::add-line:horizontal,
            QScrollBar::sub-line:horizontal,
            QScrollBar::add-page:horizontal,
            QScrollBar::sub-page:horizontal {
                width: 0px;
                height: 0px;
                background: transparent;
            }
            QMenu {
                color: #fff5d6;
                background-color: rgba(20, 22, 44, 252);
                border: 1px solid rgba(217, 179, 104, 0.35);
                border-radius: 12px;
                padding: 6px;
                font-family: "Microsoft YaHei UI", "Microsoft YaHei", sans-serif;
                font-size: 13px;
                font-weight: 600;
            }
            QMenu::item {
                color: #fff5d6;
                background: transparent;
                padding: 8px 26px 8px 12px;
                border-radius: 8px;
                min-width: 150px;
            }
            QMenu::item:selected {
                color: #d9b368;
                background: rgba(217, 179, 104, 0.15);
            }
            QMenu::item:disabled {
                color: rgba(166, 173, 200, 0.42);
            }
            QMenu::separator {
                height: 1px;
                background: rgba(217, 179, 104, 0.15);
                margin: 5px 8px;
            }
            #symbolButton {
                background: transparent;
                border: none;
            }
            #symbolButton:hover {
                background: transparent;
                border: none;
            }
            #symbolButton[pressed="true"] {
                background: transparent;
                border: none;
            }
            #sortBar {
                background: transparent;
                border: none;
            }
            QPushButton#primaryButton {
                background: transparent;
                border: none;
                color: #d9b368;
            }
            QPushButton#primaryButton:hover {
                background: transparent;
                border: none;
            }
            #addBox {
                background: transparent;
                border: none;
            }
            QTextEdit, QLineEdit {
                color: #fff5d6;
                background: transparent;
                border: none;
                padding: 0px;
                font-size: 13px;
            }
            QTextEdit:focus, QLineEdit:focus {
                background: transparent;
                border: none;
            }
            QCheckBox {
                min-width: 46px;
                min-height: 26px;
                spacing: 0px;
            }
            QCheckBox::indicator {
                width: 0px;
                height: 0px;
            }
            QCheckBox::indicator:hover {
                background: transparent;
                border: none;
            }
            QCheckBox::indicator:checked {
                background: transparent;
                border: none;
            }
            #settingsTitle { font-size: 16px; font-weight: 600; color: #d9b368; }
            #settingLabel { font-size: 14px; font-weight: 600; color: #fff5d6; }
            #settingDesc { font-size: 12px; color: #a6adc8; }
            """
        else:
            qss = """
            #panel {
                background: transparent;
                border: none;
            }
            #titlebar {
                background: transparent;
                border: none;
            }
            #pinIcon { color: #5A4E6B; font-size: 14px; }
            * { font-family: "Microsoft YaHei UI", "Microsoft YaHei", sans-serif; }
            QLabel { color: #5A4E6B; }
            QToolButton {
                background: transparent;
                color: #5A4E6B;
                border: 1px solid transparent;
                border-radius: 9px;
                padding: 5px 12px;
                font-size: 13px;
                font-weight: 600;
            }
            QPushButton {
                background: transparent;
                color: #5A4E6B;
                border: none;
                padding: 5px 12px;
                font-size: 13px;
                font-weight: 600;
            }
            QToolButton:hover {
                background: rgba(198, 122, 37, 0.08);
                border-color: transparent;
                color: #C67A25;
            }
            QPushButton:hover {
                background: transparent;
                border: none;
                color: #C67A25;
            }
            QToolButton:pressed {
                background: rgba(198, 122, 37, 0.15);
            }
            QPushButton:pressed {
                background: transparent;
                border: none;
            }
            #titlebar QToolButton {
                padding: 0px;
                font-family: "Segoe UI Symbol", "Microsoft YaHei UI", sans-serif;
                font-size: 15px;
            }
            QToolButton#titleIconButton {
                font-size: 16px;
            }
            QToolButton#closeButton {
                padding: 0px;
                font-size: 18px;
            }
            QToolButton#closeButton:hover { background: #e03030; color: white; border-color: transparent; }
            QTabBar::tab {
                color: #968C9E;
                background: transparent;
                padding: 8px 16px 12px 16px;
                border-radius: 9px;
                margin-right: 4px;
                border: 1px solid transparent;
                font-size: 14px;
                font-weight: 600;
            }
            QTabBar::tab:hover {
                color: #C67A25;
                background: rgba(198, 122, 37, 0.05);
            }
            QTabBar::tab:selected {
                color: #A86015;
                background: transparent;
            }
            QScrollArea, QWidget { background: transparent; }
            QScrollBar:vertical {
                background: transparent;
                width: 8px;
                margin: 4px 1px 4px 1px;
            }
            QScrollBar::handle:vertical {
                background: rgba(195, 180, 210, 0.35);
                border-radius: 4px;
                min-height: 24px;
            }
            QScrollBar::handle:vertical:hover {
                background: rgba(195, 180, 210, 0.55);
            }
            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,
            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {
                height: 0px;
                background: transparent;
            }
            QScrollBar:horizontal {
                height: 0px;
                background: transparent;
            }
            QScrollBar::handle:horizontal,
            QScrollBar::add-line:horizontal,
            QScrollBar::sub-line:horizontal,
            QScrollBar::add-page:horizontal,
            QScrollBar::sub-page:horizontal {
                width: 0px;
                height: 0px;
                background: transparent;
            }
            QMenu {
                color: #5A4E6B;
                background-color: rgba(252, 250, 255, 252);
                border: 1px solid rgba(195, 180, 210, 0.35);
                border-radius: 12px;
                padding: 6px;
                font-family: "Microsoft YaHei UI", "Microsoft YaHei", sans-serif;
                font-size: 13px;
                font-weight: 600;
            }
            QMenu::item {
                color: #5A4E6B;
                background: transparent;
                padding: 8px 26px 8px 12px;
                border-radius: 8px;
                min-width: 150px;
            }
            QMenu::item:selected {
                color: #C67A25;
                background: rgba(198, 122, 37, 0.08);
            }
            QMenu::item:disabled {
                color: rgba(195, 180, 210, 0.45);
            }
            QMenu::separator {
                height: 1px;
                background: rgba(195, 180, 210, 0.20);
                margin: 5px 8px;
            }
            #symbolButton {
                background: transparent;
                border: none;
            }
            #symbolButton:hover {
                background: transparent;
                border: none;
            }
            #symbolButton[pressed="true"] {
                background: transparent;
                border: none;
            }
            #sortBar {
                background: transparent;
                border: none;
            }
            QPushButton#primaryButton {
                background: transparent;
                border: none;
                color: #C67A25;
            }
            QPushButton#primaryButton:hover {
                background: transparent;
                border: none;
            }
            #addBox {
                background: transparent;
                border: none;
            }
            QTextEdit, QLineEdit {
                color: #5A4E6B;
                background: transparent;
                border: none;
                padding: 0px;
                font-size: 13px;
            }
            QTextEdit:focus, QLineEdit:focus {
                background: transparent;
                border: none;
            }
            QCheckBox {
                min-width: 46px;
                min-height: 26px;
                spacing: 0px;
            }
            QCheckBox::indicator {
                width: 0px;
                height: 0px;
            }
            QCheckBox::indicator:hover {
                background: transparent;
                border: none;
            }
            QCheckBox::indicator:checked {
                background: transparent;
                border: none;
            }
            #settingsTitle { font-size: 16px; font-weight: 600; color: #C67A25; }
            #settingLabel { font-size: 14px; font-weight: 600; color: #5A4E6B; }
            #settingDesc { font-size: 12px; color: #968C9E; }
            """
        self.setStyleSheet(self._scale_qss(qss))


